# Generated by Django 5.1.7 on 2026-05-25 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('num_agents', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100000)])),
                ('num_edges', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество связей')),
                ('directed', models.CharField(choices=[('undirected', 'Ненаправленный'), ('directed', 'Направленный')], default='undirected', max_length=20)),
                ('weight_type', models.CharField(choices=[('unweighted', 'Без весов'), ('weighted', 'Взвешенный')], default='unweighted', max_length=20)),
                ('balance_type', models.CharField(choices=[('balanced', 'Сбалансированный'), ('unbalanced', 'Несбалансированный')], default='balanced', max_length=20)),
                ('weight_min', models.FloatField(blank=True, default=0.1, null=True)),
                ('weight_max', models.FloatField(blank=True, default=1.0, null=True)),
                ('graph_data', models.JSONField(blank=True, null=True)),
                ('structural_effect', models.FloatField(blank=True, null=True)),
                ('functional_effect', models.FloatField(blank=True, null=True)),
                ('total_effect', models.FloatField(blank=True, null=True)),
                ('efficiency', models.FloatField(blank=True, null=True, verbose_name='Эффективность цепочки поставок')),
                ('business_value', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('synergy_factor', models.FloatField(blank=True, null=True)),
                ('economic_impact', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Модель сетевого эффекта',
                'verbose_name_plural': 'Модели сетевых эффектов',
                'ordering': ['-created_at'],
            },
        ),
    ]
