# Generated by Django 5.1.7 on 2026-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmodel',
            name='weight_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний вес связи'),
        ),
    ]
