# Generated by Django 6.0.5 on 2026-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_graphmodel_weight_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphmodel',
            name='balance_type',
            field=models.CharField(choices=[('balanced', 'Симметричный (для направленного графа)'), ('unbalanced', 'Несимметричный')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='graphmodel',
            name='weight_type',
            field=models.CharField(choices=[('unweighted', 'Без весов (все веса = 1)'), ('weighted', 'Взвешенный (случайные веса)')], default='unweighted', max_length=20),
        ),
    ]
